locale: 'nl'
backend:
  name: git-gateway

# navigate to /admin/# instead of /admin# to see admin panel
local_backend: true

media_folder: "site/static/media" # Folder where user uploaded files should go
public_folder: "media" # Url prefix saved when uploading / choosing media

logo_url: "/img/logo.svg"

collections: # A list of collections the CMS should be able to edit
  - name: pages
    label: Content
    files:

      - file: site/content/_index.md
        name: home
        label: Home Page
        fields:

          - label: Titel
            name: title
            widget: markdown
            minimal: true
          - label: Subtitel
            name: subtitle
            widget: markdown
            minimal: true
          - label: Images
            name: images
            widget: object
            fields:
              - label: Image 1
                name: image1
                widget: image
              - label: Image 2
                name: image2
                widget: image
              - label: Image 3
                name: image3
                widget: image

          - label: Groepslessen
            name: groupLessons
            widget: object
            fields:
              - label: Afbeelding
                name: image
                widget: image
              - label: Bescrijving
                name: description
                widget: markdown
                minimal: true

          - label: LesBlokken
            name: lessonGroups
            widget: list
            fields:
              - label: Lessen
                name: lessons
                widget: list
                fields:
                  - {label: Vaardigheid, name: name, widget: string}
                  - {label: Beschrijving, name: description, widget: markdown, minimal: true}
                  - {label: Afbeelding, name: image, widget: image}
              - label: Docent
                name: teacher
                widget: object
                fields:
                  - {label: Naam, name: name, widget: string}
                  - {label: Afbeelding, name: image, widget: image}
                  - label: prestaties
                    name: achievements
                    widget: list
                    fields:
                      - {label: Icoon, name: icon, widget: image}
                      - {label: beschrijving, name: description, widget: markdown, minimal: true}

          - label: Getuigenissen
            name: testimonials
            widget: list
            fields:
              - label: Quote
                name: quote
                widget: string
              - label: Author
                name: author
                widget: string

          - label: SEO
            name: seo
            widget: object
            fields:
              - label: Beschrijving
                name: description
                widget: text
                hint: Deze beschrijving wordt gelezen door google en is te zien in het google zoekresultaat.
                minimal: true
              - label: Afbeelding
                name: image
                hint: Deze afbeelding krijg je te zien als je een link deelt naar je website (op bijvoorbeeld Facebook of WhatsApp)
                widget: image

      - file: site/data/pricing.yml
        name: pricing
        label: Tarieven
        fields:
          - label: Paketten
            name: pricing_models
            widget: list
            fields:
              - { label: Naam, name: name, widget: string }
              - { label: Locatie, name: location, widget: string }
              - { label: Prijs < 21, name: priceChildren, widget: string, hint: "Voorbeeld: 17,50 of 20,-" }
              - { label: Prijs > 21, name: priceAdults, widget: string, hint: "Voorbeeld: 17,50 of 20,-" }
              - { label: Prijs ondertitel, name: priceSubtitle, widget: string, hint: "Voorbeeld: / 45min" }
              - label: Kenmerken
                name: features
                widget: list
                fields:
                  - { label: Kenmerk, name: name, widget: markdown, minimal: true }


      - file: "site/content/contact/_index.md"
        name: "contact"
        label: "Contact Page"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
