backend:
  name: git-gateway

# navigate to /admin/# instead of /admin# to see admin panel
local_backend: true

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        name: "home"
        label: "Home Page"
        fields:
          - label: Title
            name: title
            widget: markdown
            minimal: true
          - label: Subtitle
            name: subtitle
            widget: markdown
            minimal: true
          - label: Images
            name: images
            widget: object
            fields:
              - label: Image 1
                name: image1
                widget: image
              - label: Image 2
                name: image2
                widget: image
              - label: Image 3
                name: image3
                widget: image
          - label: Groepslessen
            name: groupLessons
            widget: object
            fields:
              - label: Afbeelding
                name: image
                widget: image
              - label: Bescrijving
                name: description
                widget: markdown
                minimal: true
          - label: Testimonials
            name: testimonials
            widget: list
            fields:
              - label: Quote
                name: quote
                widget: string
              - label: Author
                name: author
                widget: string
          - label: Pricing
            name: pricing
            widget: object
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Description
                name: description
                widget: string
              - label: Plans
                name: plans
                widget: list
                fields:
                  - label: Plan
                    name: plan
                    widget: string
                  - label: Price
                    name: price
                    widget: string
                  - label: Description
                    name: description
                    widget: string
                  - label: Items
                    name: items
                    widget: list
      - file: "site/content/contact/_index.md"
        name: "contact"
        label: "Contact Page"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
